version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      - PMA_HOST=ballast.proxy.rlwy.net
      - PMA_PORT=31708
      - PMA_USER=root
      - PMA_PASSWORD=vRZKwRWdLjjUgSlMgoonxeeOsPojlbJy